# Generated by Django 5.0.6 on 2024-07-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('createTime', models.DateField(auto_now_add=True, verbose_name='用户创建时间')),
                ('email', models.EmailField(default='2935515548@qq.com', max_length=255, verbose_name='邮箱')),
                ('phone', models.CharField(default='19993907551', max_length=20, verbose_name='电话号码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('moneyData', models.IntegerField(default=0, verbose_name='钱财')),
            ],
        ),
    ]
